input {
  http {
    port => 50001
    threads => 16
    max_pending_requests => 500
  }
}

filter {
    json {
        source => "message"
    }

    if [parsed_event] {
        mutate {
            rename => { "[parsed_event][deployment_id]" => "deployment_id" }
            rename => { "[parsed_event][nivel]" => "nivel" }
            rename => { "[parsed_event][mensaje]" => "mensaje" }
            rename => { "[parsed_event][timestamp]" => "timestamp" }
        }
    }

    # Analizar la fecha si el campo timestamp existe
    if [timestamp] {
        date {
            match => ["timestamp", "ISO8601"]
            target => "@timestamp"
        }
    }

    # Eliminar campos innecesarios
    mutate {
        remove_field => ["parsed_event", "timestamp"]
    }
}

output {
    stdout { codec => rubydebug }
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        user => "elastic"
        password => "${LOGSTASH_INTERNAL_PASSWORD}"
        index => "jenkins-v2-logs-%{+YYYY.MM.dd}"
    }
}
