input {
    http {
        port => 50000
        codec => json
    }
}

filter {
    # Parsear el JSON contenido en event.original
    json {
        source => "[event][original]"
        target => "parsed_event"
    }

    mutate {
        replace => { "service" => "jenkins" }
        replace => { "deployment_id" => "%{[parsed_event][deployment_id]}" }
        replace => { "nivel" => "%{[parsed_event][nivel]}" }
        replace => { "mensaje" => "%{[parsed_event][mensaje]}" }
        replace => { "timestamp" => "%{[parsed_event][timestamp]}" }
    }

    date {
        match => ["[parsed_event][timestamp]", "ISO8601"]
        target => "@timestamp"
    }

   

    # Opcional: Eliminar campos innecesarios
    mutate {
        remove_field => ["parsed_event", "[event][original]", "timestamp"]
    }
}

output {
    elasticsearch {
        hosts => "http://elasticsearch:9200"
        user => "elastic"
        password => "${LOGSTASH_INTERNAL_PASSWORD}"
        index => "jenkins-logs-%{+YYYY.MM.dd}"
    }
    stdout { codec => rubydebug }
}
